//
//  PhotoDetailModels.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PhotoDetail {
    enum ShortName {
        struct Response {
            var name: String
        }
        struct ViewModel {
            var name: String
        }
    }
    enum FullName {
        struct Response {
            var name: String
        }
        struct ViewModel {
            var name: String
        }
    }
    enum Image {
        struct Request {
            var url: String
        }
        struct Response {
            var image: UIImage
        }
        struct ViewModel {
            var image: UIImage
        }
    }
}
