//
//  PhotoDetailInteractor.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDetailBusinessLogic {
    func doSomething(request: PhotoDetail.Something.Request)
}

protocol PhotoDetailDataStore {
    //var name: String { get set }
}

class PhotoDetailInteractor: PhotoDetailBusinessLogic, PhotoDetailDataStore {
    var presenter: PhotoDetailPresentationLogic?
    var worker: PhotoDetailWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: PhotoDetail.Something.Request) {
        worker = PhotoDetailWorker()
        worker?.doSomeWork()
    
        let response = PhotoDetail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
