//
//  PhotoDetailWorker.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class PhotoDetailWorker {
    func downloadPhoto(on url: String, completion: @escaping (_ result: Result<UIImage, InternalErrors>) -> Void) {
        ConnectionUtil.downloadImage(url: url) { (result: Result<UIImage, InternalErrors>) in
            completion(result)
        }
    }
}
