//
//  PhotoDetailPresenter.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhotoDetailPresentationLogic {
    func presentSomething(response: PhotoDetail.Something.Response)
}

class PhotoDetailPresenter: PhotoDetailPresentationLogic {
    weak var viewController: PhotoDetailDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: PhotoDetail.Something.Response) {
        let viewModel = PhotoDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
