//
//  RoverPhotosModels.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RoverPhotos {
    enum Data {
        struct Request {
            var roverName: String
            var date: Date
        }
    }
    enum Image {
        struct Request {
            var url: String
        }
        struct Response {
            var image: UIImage
            var indexPath: IndexPath
        }
        struct ViewModel {
            var image: UIImage
            var indexPath: IndexPath
        }
    }
}
