//
//  RoverPhotosRouter.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RoverPhotosRoutingLogic {
    func routeToPhotoDetail(segue: UIStoryboardSegue?)
}

protocol RoverPhotosDataPassing {
    var dataStore: RoverPhotosDataStore? { get }
}

class RoverPhotosRouter: NSObject, RoverPhotosRoutingLogic, RoverPhotosDataPassing {
    weak var viewController: RoverPhotosViewController?
    var dataStore: RoverPhotosDataStore?

    //MARK: - Routing
    func routeToPhotoDetail(segue: UIStoryboardSegue?) {
        guard let segue = segue else { return }
        let destinationVC = segue.destination as! PhotoDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(source: dataStore!, destination: &destinationDS)
    }

    //MARK: - Passing data
    func passDataToDetail(source: RoverPhotosDataStore, destination: inout PhotoDetailDataStore) {
        let selectedIndex = viewController?.collectionViewPhotos.indexPathsForSelectedItems?.first?.row ?? 0
        destination.photo = source.photos?[selectedIndex]
    }
}
