//
//  RoverPhotosViewController.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RoverPhotosDisplayLogic: class {
    func displaySomething(viewModel: RoverPhotos.Something.ViewModel)
}

class RoverPhotosViewController: UIViewController, RoverPhotosDisplayLogic {
    var interactor: RoverPhotosBusinessLogic?
    var router: (NSObjectProtocol & RoverPhotosRoutingLogic & RoverPhotosDataPassing)?

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = RoverPhotosInteractor()
        let presenter = RoverPhotosPresenter()
        let router = RoverPhotosRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }

    // MARK: Do something

    @IBOutlet weak var segmentedControlRover: UISegmentedControl!
    @IBOutlet weak var collectionViewPhotos: UICollectionView!

    func doSomething() {
        let request = RoverPhotos.Something.Request()
        interactor?.doSomething(request: request)
    }

    func displaySomething(viewModel: RoverPhotos.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
