//
//  RoverPhotosPresenter.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RoverPhotosPresentationLogic {
    func presentSomething(response: RoverPhotos.Something.Response)
}

class RoverPhotosPresenter: RoverPhotosPresentationLogic {
    weak var viewController: RoverPhotosDisplayLogic?

    // MARK: Do something

    func presentSomething(response: RoverPhotos.Something.Response) {
        let viewModel = RoverPhotos.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
