//
//  RoverPhotosInteractor.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RoverPhotosBusinessLogic {
    func doSomething(request: RoverPhotos.Something.Request)
}

protocol RoverPhotosDataStore {
    //var name: String { get set }
}

class RoverPhotosInteractor: RoverPhotosBusinessLogic, RoverPhotosDataStore {
    var presenter: RoverPhotosPresentationLogic?
    var worker: RoverPhotosWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: RoverPhotos.Something.Request) {
        worker = RoverPhotosWorker()
        worker?.doSomeWork()

        let response = RoverPhotos.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
