//
//  RoverPhotosPresenter.swift
//  NASA Probes
//
//  Created by Matheus Cardoso kuhn on 19/04/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RoverPhotosPresentationLogic {
    func presentPhotos()
    func show(response: RoverPhotos.Image.Response)
    func presentError(error: Error)
}

class RoverPhotosPresenter: RoverPhotosPresentationLogic {
    weak var viewController: RoverPhotosDisplayLogic?

    func presentPhotos() {
        viewController?.refreshCollectionView()
    }
    
    func show(response: RoverPhotos.Image.Response) {
        let viewModel = RoverPhotos.Image.ViewModel(image: response.image, indexPath: response.indexPath)
        viewController?.displayPhoto(viewModel: viewModel)
    }
    
    func presentError(error: Error) {
        viewController?.display(error: error)
    }
}
